[rospy.client][INFO] 2021-10-22 12:56:24,417: init_node, name[/ss42/velocity_to_pose_node], pid[1616]
[xmlrpc][INFO] 2021-10-22 12:56:24,420: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-10-22 12:56:24,423: Started XML-RPC server [http://ss42.local:42167/]
[rospy.init][INFO] 2021-10-22 12:56:24,424: ROS Slave URI: [http://ss42.local:42167/]
[rospy.impl.masterslave][INFO] 2021-10-22 12:56:24,425: _ready: http://ss42.local:42167/
[rospy.registration][INFO] 2021-10-22 12:56:24,431: Registering with master node http://ss42.local:11311/
[xmlrpc][INFO] 2021-10-22 12:56:24,432: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2021-10-22 12:56:24,526: registered with master
[rospy.rosout][INFO] 2021-10-22 12:56:24,528: initializing /rosout core topic
[rospy.rosout][INFO] 2021-10-22 12:56:24,546: connected to core topic /rosout
[rospy.simtime][INFO] 2021-10-22 12:56:24,557: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2021-10-22 12:56:24,633: [/ss42/velocity_to_pose_node] Initialized.
[rospy.internal][INFO] 2021-10-22 12:56:24,794: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2021-10-22 12:56:30,651: topic[/ss42/forward_kinematics_node/velocity] adding connection to [http://ss42.local:35230/], count 0
[rospy.core][INFO] 2021-10-22 12:57:53,491: signal_shutdown [signal-2]
[rospy.internal][INFO] 2021-10-22 12:57:53,563: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-10-22 12:57:53,567: topic[/ss42/forward_kinematics_node/velocity] removing connection to http://ss42.local:35230/
[rospy.impl.masterslave][INFO] 2021-10-22 12:57:53,568: signal-2
[rospy.internal][ERROR] 2021-10-22 12:57:53,572: Unable to initiate TCP/IP socket to ss42.local:44792 (http://ss42.local:35230/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.core][INFO] 2021-10-22 12:57:54,137: signal_shutdown [atexit]
