[rospy.client][INFO] 2021-12-06 08:40:25,134: init_node, name[/ss42/wheels_driver_node], pid[5228]
[xmlrpc][INFO] 2021-12-06 08:40:25,144: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2021-12-06 08:40:25,163: ROS Slave URI: [http://ss42.local:34007/]
[xmlrpc][INFO] 2021-12-06 08:40:25,164: Started XML-RPC server [http://ss42.local:34007/]
[rospy.impl.masterslave][INFO] 2021-12-06 08:40:25,164: _ready: http://ss42.local:34007/
[xmlrpc][INFO] 2021-12-06 08:40:25,184: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2021-12-06 08:40:25,187: Registering with master node http://ss42.local:11311/
[rospy.init][INFO] 2021-12-06 08:40:25,264: registered with master
[rospy.rosout][INFO] 2021-12-06 08:40:25,265: initializing /rosout core topic
[rospy.rosout][INFO] 2021-12-06 08:40:25,297: connected to core topic /rosout
[rospy.simtime][INFO] 2021-12-06 08:40:25,326: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2021-12-06 08:40:25,414: [/ss42/wheels_driver_node] Initializing 
[rospy.internal][INFO] 2021-12-06 08:40:25,583: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2021-12-06 08:40:26,340: topic[/ss42/wheels_driver_node/emergency_stop] adding connection to [http://ss42.local:37360/], count 0
[rosout][INFO] 2021-12-06 08:40:30,941: [%s] Emergency Stop Activated
[rosout][INFO] 2021-12-06 08:40:30,948: [%s] Emergency Stop Released
[rospy.internal][INFO] 2021-12-06 08:40:32,435: topic[/ss42/wheels_driver_node/wheels_cmd] adding connection to [http://ss42.local:35479/], count 0
[rosout][INFO] 2021-12-06 08:40:34,483: [%s] Emergency Stop Activated
[rosout][INFO] 2021-12-06 08:40:35,961: [%s] Emergency Stop Released
[rospy.internal][WARNING] 2021-12-06 09:22:18,949: Unknown error initiating TCP/IP socket to ss42.local:34990 (http://ss42.local:37360/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2021-12-06 09:22:19,010: topic[/ss42/wheels_driver_node/emergency_stop] removing connection to http://ss42.local:37360/
[rospy.core][INFO] 2021-12-06 09:22:19,072: signal_shutdown [signal-2]
[rosout][INFO] 2021-12-06 09:22:19,093: [/ss42/wheels_driver_node] Shutting down.
[rospy.internal][WARNING] 2021-12-06 09:22:19,317: Unknown error initiating TCP/IP socket to ss42.local:36706 (http://ss42.local:35479/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 364, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2021-12-06 09:22:19,320: topic[/ss42/wheels_driver_node/wheels_cmd] removing connection to http://ss42.local:35479/
[rospy.internal][INFO] 2021-12-06 09:22:19,328: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2021-12-06 09:22:19,339: signal-2
[rospy.core][INFO] 2021-12-06 09:22:19,818: signal_shutdown [atexit]
