[rospy.client][INFO] 2021-10-22 12:01:44,153: [32minit_node, name[/ss42/raw_cam_info_reader_node], pid[2262][0m
[xmlrpc][INFO] 2021-10-22 12:01:44,154: [32mXML-RPC server binding to 0.0.0.0:0[0m
[xmlrpc][INFO] 2021-10-22 12:01:44,157: [32mStarted XML-RPC server [http://ss42.local:38833/][0m
[rospy.init][INFO] 2021-10-22 12:01:44,158: [32mROS Slave URI: [http://ss42.local:38833/][0m
[rospy.impl.masterslave][INFO] 2021-10-22 12:01:44,158: [32m_ready: http://ss42.local:38833/[0m
[xmlrpc][INFO] 2021-10-22 12:01:44,161: [32mxml rpc node: starting XML-RPC server[0m
[rospy.registration][INFO] 2021-10-22 12:01:44,164: [32mRegistering with master node http://ss42.local:11311/[0m
[rospy.init][INFO] 2021-10-22 12:01:44,259: [32mregistered with master[0m
[rospy.rosout][INFO] 2021-10-22 12:01:44,260: [32minitializing /rosout core topic[0m
[rospy.rosout][INFO] 2021-10-22 12:01:44,271: [32mconnected to core topic /rosout[0m
[rospy.simtime][INFO] 2021-10-22 12:01:44,277: [32m/use_sim_time is not set, will not subscribe to simulated time [/clock] topic[0m
[rosout][INFO] 2021-10-22 12:01:44,308: [32m[/ss42/raw_cam_info_reader_node] ~config = baseline [0m
[rosout][INFO] 2021-10-22 12:01:44,328: [32m[/ss42/raw_cam_info_reader_node] ~cali_file_name = ss42 [0m
[rosout][INFO] 2021-10-22 12:01:44,341: [32m[/ss42/raw_cam_info_reader_node] ~image_type = raw [0m
[rosout][WARNING] 2021-10-22 12:01:44,362: [33m[/ss42/raw_cam_info_reader_node] Can't find calibration file: /home/robotikabot/duckiefleet/calibrations/camera_intrinsic/ss42.yaml.
Using default calibration instead.[0m
[rosout][INFO] 2021-10-22 12:01:44,363: [32m[/ss42/raw_cam_info_reader_node] Using calibration file: /home/robotikabot/duckiefleet/calibrations/camera_intrinsic/default.yaml[0m
[rosout][INFO] 2021-10-22 12:01:44,409: [32m[/ss42/raw_cam_info_reader_node] CameraInfo: header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: "/ss42/camera_optical_frame"
height: 480
width: 640
distortion_model: "plumb_bob"
D: [-0.2565888993516047, 0.04481160508242147, -0.00505275149956019, 0.001308569367976665, 0]
K: [307.7379294605756, 0, 329.692367951685, 0, 314.9827773443905, 244.4605588877848, 0, 0, 1]
R: [1, 0, 0, 0, 1, 0, 0, 0, 1]
P: [210.1107940673828, 0, 327.2577820024981, 0, 0, 253.8408660888672, 239.9969353923052, 0, 0, 0, 1, 0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False[0m
[rosout][WARNING] 2021-10-22 12:01:44,410: [33m[/ss42/raw_cam_info_reader_node] ==============Image[0m
[rospy.internal][INFO] 2021-10-22 12:01:44,462: [32mtopic[/rosout] adding connection to [/rosout], count 0[0m
[rospy.internal][INFO] 2021-10-22 12:01:44,467: [32mtopic[/ss42/camera_node/image/raw] adding connection to [http://ss42.local:40213/], count 0[0m
[rospy.internal][ERROR] 2021-10-22 12:19:19,741: [31mUnable to initiate TCP/IP socket to ss42.local:33982 (http://ss42.local:40213/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down
[0m
[rospy.internal][INFO] 2021-10-22 12:19:19,896: [32mtopic[/ss42/camera_node/image/raw] adding connection to [http://ss42.local:44068/], count 1[0m
[rospy.core][INFO] 2021-10-22 12:19:20,577: [32msignal_shutdown [signal-2][0m
[rosout][INFO] 2021-10-22 12:19:20,577: [32m[/ss42/raw_cam_info_reader_node] Shutdown.[0m
[rospy.internal][INFO] 2021-10-22 12:19:20,613: [32mtopic[/rosout] removing connection to /rosout[0m
[rospy.internal][INFO] 2021-10-22 12:19:20,614: [32mtopic[/ss42/camera_node/image/raw] removing connection to http://ss42.local:40213/[0m
[rospy.internal][WARNING] 2021-10-22 12:19:20,621: [33mUnknown error initiating TCP/IP socket to ss42.local:40265 (http://ss42.local:44068/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'
[0m
[rospy.internal][INFO] 2021-10-22 12:19:20,624: [32mtopic[/ss42/camera_node/image/raw] removing connection to http://ss42.local:44068/[0m
[rospy.impl.masterslave][INFO] 2021-10-22 12:19:20,625: [32msignal-2[0m
[rospy.core][INFO] 2021-10-22 12:19:21,247: [32msignal_shutdown [atexit][0m
