[rospy.client][INFO] 2021-12-06 08:38:27,280: init_node, name[/ss42/wheels_driver_node], pid[1600]
[xmlrpc][INFO] 2021-12-06 08:38:27,299: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2021-12-06 08:38:27,302: ROS Slave URI: [http://ss42.local:40319/]
[xmlrpc][INFO] 2021-12-06 08:38:27,303: Started XML-RPC server [http://ss42.local:40319/]
[rospy.impl.masterslave][INFO] 2021-12-06 08:38:27,304: _ready: http://ss42.local:40319/
[xmlrpc][INFO] 2021-12-06 08:38:27,314: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2021-12-06 08:38:27,318: Registering with master node http://ss42.local:11311/
[rospy.init][INFO] 2021-12-06 08:38:27,404: registered with master
[rospy.rosout][INFO] 2021-12-06 08:38:27,405: initializing /rosout core topic
[rospy.rosout][INFO] 2021-12-06 08:38:27,437: connected to core topic /rosout
[rospy.simtime][INFO] 2021-12-06 08:38:27,476: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2021-12-06 08:38:27,542: [/ss42/wheels_driver_node] Initializing 
[rospy.internal][INFO] 2021-12-06 08:38:27,703: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2021-12-06 08:38:28,653: topic[/ss42/wheels_driver_node/emergency_stop] adding connection to [http://ss42.local:36461/], count 0
[rospy.internal][INFO] 2021-12-06 08:38:36,124: topic[/ss42/wheels_driver_node/wheels_cmd] adding connection to [http://ss42.local:41758/], count 0
[rospy.core][INFO] 2021-12-06 08:39:50,835: signal_shutdown [signal-2]
[rosout][INFO] 2021-12-06 08:39:50,861: [/ss42/wheels_driver_node] Shutting down.
[rospy.internal][ERROR] 2021-12-06 08:39:50,969: Unable to initiate TCP/IP socket to ss42.local:41254 (http://ss42.local:36461/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2021-12-06 08:39:51,081: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-12-06 08:39:51,081: topic[/ss42/wheels_driver_node/emergency_stop] removing connection to http://ss42.local:36461/
[rospy.internal][WARNING] 2021-12-06 08:39:51,085: Unknown error initiating TCP/IP socket to ss42.local:39774 (http://ss42.local:41758/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 364, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2021-12-06 08:39:51,086: topic[/ss42/wheels_driver_node/wheels_cmd] removing connection to http://ss42.local:41758/
[rospy.impl.masterslave][INFO] 2021-12-06 08:39:51,097: signal-2
[rospy.core][INFO] 2021-12-06 08:39:51,610: signal_shutdown [atexit]
