[rospy.client][INFO] 2021-12-06 08:38:37,889: init_node, name[/ss42/lane_pose_visualizer_node], pid[1643]
[xmlrpc][INFO] 2021-12-06 08:38:37,891: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-12-06 08:38:37,892: Started XML-RPC server [http://ss42.local:45342/]
[rospy.init][INFO] 2021-12-06 08:38:37,893: ROS Slave URI: [http://ss42.local:45342/]
[rospy.impl.masterslave][INFO] 2021-12-06 08:38:37,893: _ready: http://ss42.local:45342/
[rospy.registration][INFO] 2021-12-06 08:38:37,897: Registering with master node http://ss42.local:11311/
[xmlrpc][INFO] 2021-12-06 08:38:37,900: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2021-12-06 08:38:37,994: registered with master
[rospy.rosout][INFO] 2021-12-06 08:38:37,995: initializing /rosout core topic
[rospy.rosout][INFO] 2021-12-06 08:38:38,006: connected to core topic /rosout
[rospy.simtime][INFO] 2021-12-06 08:38:38,011: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2021-12-06 08:38:38,024: [/ss42/lane_pose_visualizer_node] Initialzing.
[rosout][INFO] 2021-12-06 08:38:38,026: [/ss42/lane_pose_visualizer_node] Vehicle name: ss42
[rosout][INFO] 2021-12-06 08:38:38,045: [/ss42/lane_pose_visualizer_node] Initialzed.
[rospy.internal][INFO] 2021-12-06 08:38:38,293: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2021-12-06 08:38:38,439: topic[/ss42/lane_filter_node/lane_pose] adding connection to [http://ss42.local:45341/], count 0
[rospy.core][INFO] 2021-12-06 08:39:49,781: signal_shutdown [signal-2]
[rosout][INFO] 2021-12-06 08:39:49,783: [/ss42/lane_pose_visualizer_node] Shutting down.
[rospy.internal][INFO] 2021-12-06 08:39:49,891: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-12-06 08:39:49,893: topic[/ss42/lane_filter_node/lane_pose] removing connection to http://ss42.local:45341/
[rospy.topics][ERROR] 2021-12-06 08:39:49,898: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2021-12-06 08:39:49,899: signal-2
[rospy.internal][WARNING] 2021-12-06 08:39:49,902: Unknown error initiating TCP/IP socket to ss42.local:37029 (http://ss42.local:45341/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.core][INFO] 2021-12-06 08:39:50,424: signal_shutdown [atexit]
