[rospy.client][INFO] 2021-12-09 13:09:58,426: [32minit_node, name[/ss42/lane_filter_node], pid[7928][0m
[xmlrpc][INFO] 2021-12-09 13:09:58,446: [32mXML-RPC server binding to 0.0.0.0:0[0m
[rospy.init][INFO] 2021-12-09 13:09:58,459: [32mROS Slave URI: [http://ss42.local:39201/][0m
[xmlrpc][INFO] 2021-12-09 13:09:58,459: [32mStarted XML-RPC server [http://ss42.local:39201/][0m
[rospy.impl.masterslave][INFO] 2021-12-09 13:09:58,462: [32m_ready: http://ss42.local:39201/[0m
[rospy.registration][INFO] 2021-12-09 13:09:58,475: [32mRegistering with master node http://ss42.local:11311/[0m
[xmlrpc][INFO] 2021-12-09 13:09:58,485: [32mxml rpc node: starting XML-RPC server[0m
[rospy.init][INFO] 2021-12-09 13:09:58,561: [32mregistered with master[0m
[rospy.rosout][INFO] 2021-12-09 13:09:58,563: [32minitializing /rosout core topic[0m
[rospy.rosout][INFO] 2021-12-09 13:09:58,601: [32mconnected to core topic /rosout[0m
[rospy.simtime][INFO] 2021-12-09 13:09:58,628: [32m/use_sim_time is not set, will not subscribe to simulated time [/clock] topic[0m
[rosout][INFO] 2021-12-09 13:09:58,731: [32m[Lane Filter] new filter config: ['lane_filter.LaneFilterHistogram', {'configuration': {'phi_max': 1.5, 'lanewidth': 0.23, 'mean_d_0': 0, 'min_max': 0.1, 'phi_min': -1.5, 'd_max': 0.3, 'sigma_phi_mask': 2.0, 'sigma_d_mask': 1.0, 'mean_phi_0': 0, 'sigma_phi_0': 0.1, 'linewidth_white': 0.05, 'linewidth_yellow': 0.025, 'delta_d': 0.02, 'd_min': -0.15, 'delta_phi': 0.1, 'sigma_d_0': 0.1, 'cov_v': 0.5}}][0m
[rospy.internal][INFO] 2021-12-09 13:09:58,858: [32mtopic[/rosout] adding connection to [/rosout], count 0[0m
[rospy.internal][INFO] 2021-12-09 13:10:01,543: [32mtopic[/ss42/ground_projection/lineseglist_out] adding connection to [http://ss42.local:36410/], count 0[0m
[rospy.internal][INFO] 2021-12-09 13:10:01,590: [32mtopic[/ss42/lane_filter_node/switch] adding connection to [http://ss42.local:36750/], count 0[0m
[rospy.internal][INFO] 2021-12-09 13:10:01,604: [32mtopic[/ss42/car_cmd_switch_node/cmd] adding connection to [http://ss42.local:42644/], count 0[0m
[rospy.internal][INFO] 2021-12-09 13:10:01,731: [32mtopic[/ss42/lane_filter_node/lane_pose] adding connection to [/ss42/lane_pose_visualizer_node], count 0[0m
[rospy.internal][INFO] 2021-12-09 13:10:01,757: [32mtopic[/ss42/lane_filter_node/lane_pose] adding connection to [/ss42/lane_controller_node], count 1[0m
[rosout][WARNING] 2021-12-09 13:39:38,532: [33mInbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.[0m
[rospy.internal][ERROR] 2021-12-09 13:39:38,545: [31mInbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 364, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[0m
[rospy.core][INFO] 2021-12-09 13:39:38,554: [32msignal_shutdown [signal-2][0m
[rosout][INFO] 2021-12-09 13:39:38,555: [32m[LaneFilterNode] Shutdown.[0m
[rospy.internal][INFO] 2021-12-09 13:39:38,590: [32mtopic[/ss42/lane_filter_node/lane_pose] removing connection to /ss42/lane_controller_node[0m
[rospy.internal][ERROR] 2021-12-09 13:39:38,742: [31mUnable to initiate TCP/IP socket to ss42.local:42946 (http://ss42.local:36410/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down
[0m
[rospy.internal][INFO] 2021-12-09 13:39:38,755: [32mtopic[/ss42/lane_filter_node/lane_pose] removing connection to /ss42/lane_pose_visualizer_node[0m
[rospy.internal][INFO] 2021-12-09 13:39:38,757: [32mtopic[/rosout] removing connection to /rosout[0m
[rospy.internal][INFO] 2021-12-09 13:39:38,759: [32mtopic[/ss42/ground_projection/lineseglist_out] removing connection to http://ss42.local:36410/[0m
[rospy.internal][INFO] 2021-12-09 13:39:38,760: [32mtopic[/ss42/lane_filter_node/switch] removing connection to http://ss42.local:36750/[0m
[rospy.internal][INFO] 2021-12-09 13:39:38,763: [32mtopic[/ss42/car_cmd_switch_node/cmd] removing connection to http://ss42.local:42644/[0m
[rospy.impl.masterslave][INFO] 2021-12-09 13:39:38,764: [32msignal-2[0m
[rospy.internal][WARNING] 2021-12-09 13:39:38,770: [33mUnknown error initiating TCP/IP socket to ss42.local:46066 (http://ss42.local:42644/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'
[0m
[rospy.core][INFO] 2021-12-09 13:39:39,235: [32msignal_shutdown [atexit][0m
