[rospy.client][INFO] 2021-12-08 11:39:54,715: [32minit_node, name[/ss42/inverse_kinematics_node], pid[3093][0m
[xmlrpc][INFO] 2021-12-08 11:39:54,734: [32mXML-RPC server binding to 0.0.0.0:0[0m
[xmlrpc][INFO] 2021-12-08 11:39:54,736: [32mStarted XML-RPC server [http://ss42.local:34963/][0m
[rospy.impl.masterslave][INFO] 2021-12-08 11:39:54,737: [32m_ready: http://ss42.local:34963/[0m
[rospy.init][INFO] 2021-12-08 11:39:54,749: [32mROS Slave URI: [http://ss42.local:34963/][0m
[rospy.registration][INFO] 2021-12-08 11:39:54,763: [32mRegistering with master node http://ss42.local:11311/[0m
[xmlrpc][INFO] 2021-12-08 11:39:54,763: [32mxml rpc node: starting XML-RPC server[0m
[rospy.init][INFO] 2021-12-08 11:39:54,851: [32mregistered with master[0m
[rospy.rosout][INFO] 2021-12-08 11:39:54,852: [32minitializing /rosout core topic[0m
[rospy.rosout][INFO] 2021-12-08 11:39:54,886: [32mconnected to core topic /rosout[0m
[rospy.simtime][INFO] 2021-12-08 11:39:54,920: [32m/use_sim_time is not set, will not subscribe to simulated time [/clock] topic[0m
[rosout][WARNING] 2021-12-08 11:39:54,994: [33m[/ss42/inverse_kinematics_node] /home/robotikabot/duckiefleet/calibrations/kinematics/ss42.yaml does not exist. Using default.yaml.[0m
[rospy.internal][INFO] 2021-12-08 11:39:55,158: [32mtopic[/rosout] adding connection to [/rosout], count 0[0m
[rosout][INFO] 2021-12-08 11:39:55,347: [32m[/ss42/inverse_kinematics_node] ~gain = 1.0 [0m
[rosout][INFO] 2021-12-08 11:39:55,383: [32m[/ss42/inverse_kinematics_node] ~trim = 0.0 [0m
[rosout][INFO] 2021-12-08 11:39:55,417: [32m[/ss42/inverse_kinematics_node] ~baseline = 0.1 [0m
[rosout][INFO] 2021-12-08 11:39:55,461: [32m[/ss42/inverse_kinematics_node] ~radius = 0.0318 [0m
[rosout][INFO] 2021-12-08 11:39:55,501: [32m[/ss42/inverse_kinematics_node] ~k = 27.0 [0m
[rosout][INFO] 2021-12-08 11:39:55,539: [32m[/ss42/inverse_kinematics_node] ~limit = 1.0 [0m
[rosout][INFO] 2021-12-08 11:39:55,866: [32m[/ss42/inverse_kinematics_node] Initialized.[0m
[rosout][INFO] 2021-12-08 11:39:55,869: [32m[/ss42/inverse_kinematics_node] gain: 1.0 trim: 0.0 baseline: 0.1 radius: 0.0318 k: 27.0 limit: 1.0[0m
[rospy.internal][INFO] 2021-12-08 11:39:55,931: [32mtopic[/ss42/car_cmd_switch_node/cmd] adding connection to [http://ss42.local:41928/], count 0[0m
[rospy.internal][INFO] 2021-12-08 11:39:56,010: [32mtopic[/ss42/wheels_driver_node/wheels_cmd] adding connection to [/ss42/wheels_driver_node], count 0[0m
[rospy.internal][ERROR] 2021-12-08 14:14:12,186: [31mUnable to initiate TCP/IP socket to ss42.local:40388 (http://ss42.local:41928/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down
[0m
[rospy.core][INFO] 2021-12-08 14:14:13,984: [32msignal_shutdown [signal-2][0m
[rospy.internal][INFO] 2021-12-08 14:14:14,002: [32mtopic[/ss42/wheels_driver_node/wheels_cmd] removing connection to /ss42/wheels_driver_node[0m
[rospy.internal][INFO] 2021-12-08 14:14:14,078: [32mtopic[/rosout] removing connection to /rosout[0m
[rospy.internal][INFO] 2021-12-08 14:14:14,080: [32mtopic[/ss42/car_cmd_switch_node/cmd] removing connection to http://ss42.local:41928/[0m
[rospy.impl.masterslave][INFO] 2021-12-08 14:14:14,081: [32msignal-2[0m
[rospy.internal][WARNING] 2021-12-08 14:14:14,087: [33mUnknown error initiating TCP/IP socket to ss42.local:40388 (http://ss42.local:41928/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 364, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[0m
[rospy.core][INFO] 2021-12-08 14:14:14,686: [32msignal_shutdown [atexit][0m
