[rospy.client][INFO] 2021-12-08 14:14:45,106: init_node, name[/ss42/wheels_driver_node], pid[8057]
[xmlrpc][INFO] 2021-12-08 14:14:45,136: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2021-12-08 14:14:45,157: ROS Slave URI: [http://ss42.local:42997/]
[xmlrpc][INFO] 2021-12-08 14:14:45,157: Started XML-RPC server [http://ss42.local:42997/]
[rospy.impl.masterslave][INFO] 2021-12-08 14:14:45,159: _ready: http://ss42.local:42997/
[rospy.registration][INFO] 2021-12-08 14:14:45,207: Registering with master node http://ss42.local:11311/
[xmlrpc][INFO] 2021-12-08 14:14:45,208: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2021-12-08 14:14:45,259: registered with master
[rospy.rosout][INFO] 2021-12-08 14:14:45,260: initializing /rosout core topic
[rospy.rosout][INFO] 2021-12-08 14:14:45,291: connected to core topic /rosout
[rospy.simtime][INFO] 2021-12-08 14:14:45,330: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2021-12-08 14:14:45,428: [/ss42/wheels_driver_node] Initializing 
[rospy.internal][INFO] 2021-12-08 14:14:45,607: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2021-12-08 14:14:47,624: topic[/ss42/wheels_driver_node/emergency_stop] adding connection to [http://ss42.local:45579/], count 0
[rospy.internal][INFO] 2021-12-08 14:14:55,292: topic[/ss42/wheels_driver_node/wheels_cmd] adding connection to [http://ss42.local:35967/], count 0
[rospy.core][INFO] 2021-12-08 15:05:01,932: signal_shutdown [signal-2]
[rospy.internal][WARNING] 2021-12-08 15:05:01,802: Unknown error initiating TCP/IP socket to ss42.local:37263 (http://ss42.local:45579/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2021-12-08 15:05:02,264: topic[/ss42/wheels_driver_node/emergency_stop] removing connection to http://ss42.local:45579/
[rosout][INFO] 2021-12-08 15:05:02,132: [/ss42/wheels_driver_node] Shutting down.
[rospy.internal][INFO] 2021-12-08 15:05:02,817: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-12-08 15:05:02,820: topic[/ss42/wheels_driver_node/wheels_cmd] removing connection to http://ss42.local:35967/
[rospy.internal][WARNING] 2021-12-08 15:05:02,823: Unknown error initiating TCP/IP socket to ss42.local:44960 (http://ss42.local:35967/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.impl.masterslave][INFO] 2021-12-08 15:05:02,853: signal-2
[rospy.core][INFO] 2021-12-08 15:05:03,226: signal_shutdown [atexit]
