[rospy.client][INFO] 2021-11-21 07:08:48,552: [32minit_node, name[/ss42/lane_filter_node], pid[10836][0m
[xmlrpc][INFO] 2021-11-21 07:08:48,567: [32mXML-RPC server binding to 0.0.0.0:0[0m
[xmlrpc][INFO] 2021-11-21 07:08:48,569: [32mStarted XML-RPC server [http://ss42.local:37317/][0m
[rospy.impl.masterslave][INFO] 2021-11-21 07:08:48,571: [32m_ready: http://ss42.local:37317/[0m
[rospy.init][INFO] 2021-11-21 07:08:48,571: [32mROS Slave URI: [http://ss42.local:37317/][0m
[xmlrpc][INFO] 2021-11-21 07:08:48,586: [32mxml rpc node: starting XML-RPC server[0m
[rospy.registration][INFO] 2021-11-21 07:08:48,589: [32mRegistering with master node http://ss42.local:11311/[0m
[rospy.init][INFO] 2021-11-21 07:08:48,678: [32mregistered with master[0m
[rospy.rosout][INFO] 2021-11-21 07:08:48,682: [32minitializing /rosout core topic[0m
[rospy.rosout][INFO] 2021-11-21 07:08:48,749: [32mconnected to core topic /rosout[0m
[rospy.simtime][INFO] 2021-11-21 07:08:48,775: [32m/use_sim_time is not set, will not subscribe to simulated time [/clock] topic[0m
[rosout][INFO] 2021-11-21 07:08:48,960: [32m[Lane Filter] new filter config: ['lane_filter.LaneFilterHistogram', {'configuration': {'phi_max': 1.5, 'lanewidth': 0.23, 'mean_d_0': 0, 'min_max': 0.1, 'phi_min': -1.5, 'd_max': 0.3, 'sigma_phi_mask': 2.0, 'sigma_d_mask': 1.0, 'mean_phi_0': 0, 'sigma_phi_0': 0.1, 'linewidth_white': 0.05, 'linewidth_yellow': 0.025, 'delta_d': 0.02, 'd_min': -0.15, 'delta_phi': 0.1, 'sigma_d_0': 0.1, 'cov_v': 0.5}}][0m
[rospy.internal][INFO] 2021-11-21 07:08:49,109: [32mtopic[/rosout] adding connection to [/rosout], count 0[0m
[rospy.internal][INFO] 2021-11-21 07:08:51,530: [32mtopic[/ss42/ground_projection/lineseglist_out] adding connection to [http://ss42.local:33969/], count 0[0m
[rospy.internal][INFO] 2021-11-21 07:08:51,567: [32mtopic[/ss42/lane_filter_node/switch] adding connection to [http://ss42.local:38040/], count 0[0m
[rospy.internal][INFO] 2021-11-21 07:08:51,591: [32mtopic[/ss42/car_cmd_switch_node/cmd] adding connection to [http://ss42.local:38348/], count 0[0m
[rospy.internal][INFO] 2021-11-21 07:08:51,689: [32mtopic[/ss42/lane_filter_node/lane_pose] adding connection to [/ss42/lane_controller_node], count 0[0m
[rospy.internal][INFO] 2021-11-21 07:08:51,704: [32mtopic[/ss42/lane_filter_node/lane_pose] adding connection to [/ss42/lane_pose_visualizer_node], count 1[0m
[rospy.core][INFO] 2021-11-21 07:47:10,364: [32msignal_shutdown [signal-2][0m
[rosout][INFO] 2021-11-21 07:47:10,405: [32m[LaneFilterNode] Shutdown.[0m
[rospy.internal][INFO] 2021-11-21 07:47:10,416: [32mtopic[/ss42/lane_filter_node/lane_pose] removing connection to /ss42/lane_controller_node[0m
[rospy.internal][WARNING] 2021-11-21 07:47:10,844: [33mUnknown error initiating TCP/IP socket to ss42.local:42233 (http://ss42.local:33969/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer
[0m
[rospy.internal][INFO] 2021-11-21 07:47:10,846: [32mtopic[/ss42/ground_projection/lineseglist_out] removing connection to http://ss42.local:33969/[0m
[rospy.internal][INFO] 2021-11-21 07:47:10,940: [32mtopic[/ss42/lane_filter_node/lane_pose] removing connection to /ss42/lane_pose_visualizer_node[0m
[rospy.internal][INFO] 2021-11-21 07:47:10,942: [32mtopic[/rosout] removing connection to /rosout[0m
[rospy.internal][INFO] 2021-11-21 07:47:10,957: [32mtopic[/ss42/lane_filter_node/switch] removing connection to http://ss42.local:38040/[0m
[rospy.internal][INFO] 2021-11-21 07:47:10,963: [32mtopic[/ss42/car_cmd_switch_node/cmd] removing connection to http://ss42.local:38348/[0m
[rospy.internal][WARNING] 2021-11-21 07:47:10,966: [33mUnknown error initiating TCP/IP socket to ss42.local:45557 (http://ss42.local:38348/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'
[0m
[rospy.impl.masterslave][INFO] 2021-11-21 07:47:10,968: [32msignal-2[0m
[rospy.core][INFO] 2021-11-21 07:47:11,073: [32msignal_shutdown [atexit][0m
