[rospy.client][INFO] 2021-11-21 07:08:34,969: init_node, name[/ss42/duckiebot_visualizer], pid[10834]
[xmlrpc][INFO] 2021-11-21 07:08:35,021: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2021-11-21 07:08:35,036: ROS Slave URI: [http://ss42.local:37638/]
[xmlrpc][INFO] 2021-11-21 07:08:35,035: Started XML-RPC server [http://ss42.local:37638/]
[rospy.impl.masterslave][INFO] 2021-11-21 07:08:35,044: _ready: http://ss42.local:37638/
[xmlrpc][INFO] 2021-11-21 07:08:35,057: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2021-11-21 07:08:35,071: Registering with master node http://ss42.local:11311/
[rospy.init][INFO] 2021-11-21 07:08:35,138: registered with master
[rospy.rosout][INFO] 2021-11-21 07:08:35,140: initializing /rosout core topic
[rospy.rosout][INFO] 2021-11-21 07:08:35,195: connected to core topic /rosout
[rospy.simtime][INFO] 2021-11-21 07:08:35,261: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2021-11-21 07:08:35,407: [/ss42/duckiebot_visualizer] Initialzing.
[rospy.internal][INFO] 2021-11-21 07:08:35,459: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2021-11-21 07:08:35,571: [/ss42/duckiebot_visualizer] ~veh_name = ss42 
[rosout][INFO] 2021-11-21 07:08:35,858: [/ss42/duckiebot_visualizer] Initialzed.
[rospy.internal][INFO] 2021-11-21 07:08:50,427: topic[/ss42/ground_projection/lineseglist_out] adding connection to [http://ss42.local:33969/], count 0
[rospy.core][INFO] 2021-11-21 07:47:10,407: signal_shutdown [signal-2]
[rosout][INFO] 2021-11-21 07:47:10,423: [/ss42/duckiebot_visualizer] Shutting down.
[rospy.internal][INFO] 2021-11-21 07:47:10,795: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-11-21 07:47:10,797: topic[/ss42/ground_projection/lineseglist_out] removing connection to http://ss42.local:33969/
[rospy.topics][ERROR] 2021-11-21 07:47:10,804: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][WARNING] 2021-11-21 07:47:10,807: Unknown error initiating TCP/IP socket to ss42.local:42233 (http://ss42.local:33969/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.impl.masterslave][INFO] 2021-11-21 07:47:10,806: signal-2
[rospy.core][INFO] 2021-11-21 07:47:11,093: signal_shutdown [atexit]
